/**
 * Gemini Imagen API Client for Image Generation
 */

export interface ImagenConfig {
    apiKey: string;
    model?: string;
}

const DEFAULT_MODEL = "imagen-3.0-generate-001";

export class GeminiImagenClient {
    private apiKey: string;
    private model: string;
    private baseUrl = "https://generativelanguage.googleapis.com/v1beta";

    constructor(config: ImagenConfig) {
        this.apiKey = config.apiKey;
        this.model = config.model || DEFAULT_MODEL;
    }

    async generateImage(prompt: string): Promise<string> {
        try {
            const response = await fetch(
                `${this.baseUrl}/models/${this.model}:generateImages?key=${this.apiKey}`,
                {
                    method: "POST",
                    headers: {
                        "Content-Type": "application/json",
                    },
                    body: JSON.stringify({
                        prompt: prompt,
                        number_of_images: 1,
                        aspect_ratio: "3:4", // Portrait for receipt
                        safety_filter_level: "block_only_high",
                        person_generation: "allow_adult",
                    }),
                }
            );

            if (!response.ok) {
                const errorText = await response.text();
                throw new Error(`Gemini Imagen API error: ${response.statusText} - ${errorText}`);
            }

            const data = await response.json();

            if (!data.generatedImages || data.generatedImages.length === 0) {
                throw new Error("No images generated by Gemini Imagen");
            }

            // Convert base64 to blob URL
            const base64Image = data.generatedImages[0].imageBytes;
            const blob = base64ToBlob(base64Image, 'image/png');
            return URL.createObjectURL(blob);
        } catch (error) {
            console.error("Gemini Imagen generation error:", error);
            throw error;
        }
    }
}

/**
 * Helper function to convert base64 to Blob
 */
function base64ToBlob(base64: string, mimeType: string): Blob {
    const byteCharacters = atob(base64);
    const byteNumbers = new Array(byteCharacters.length);

    for (let i = 0; i < byteCharacters.length; i++) {
        byteNumbers[i] = byteCharacters.charCodeAt(i);
    }

    const byteArray = new Uint8Array(byteNumbers);
    return new Blob([byteArray], { type: mimeType });
}

export function getGeminiImagenClient(): GeminiImagenClient | null {
    const apiKey = import.meta.env.VITE_GEMINI_API_KEY;

    if (!apiKey) {
        console.warn("No Gemini API key configured");
        return null;
    }

    return new GeminiImagenClient({ apiKey });
}
